# JIA Cellular AI Mapping Default Configuration

# Simulation Parameters
simulation:
  time_step: 0.1  # seconds
  max_steps: 1000
  spatial_resolution: 0.001  # meters
  temperature: 310.15  # Kelvin (37°C)

# Cell Parameters
cells:
  immune:
    t_cell:
      base_count: 1000
      activation_threshold: 0.7
      proliferation_rate: 0.1
    b_cell:
      base_count: 500
      activation_threshold: 0.6
      antibody_production_rate: 0.05
  tissue:
    chondrocyte:
      base_count: 2000
      matrix_production_rate: 0.02
      apoptosis_threshold: 0.8
    fibroblast:
      base_count: 1500
      collagen_production_rate: 0.03

# AI Agent Configuration
ai_agents:
  primary:
    - name: "claude"
      role: "nucleus"
      weight: 0.4
    - name: "gpt"
      role: "cytoplasm"
      weight: 0.3
    - name: "gemini"
      role: "membrane"
      weight: 0.3
  backup:
    - name: "biobert"
      role: "reserve"
      weight: 0.2
    - name: "bart"
      role: "reserve"
      weight: 0.2

# Field Resonance Parameters
resonance:
  base_frequency: 1.0
  harmonic_scaling: 0.5
  decay_rate: 0.1
  coupling_strength: 0.8

# Weight System Parameters
weight_system:
  base_weight: 1.0
  direction_weight: 0.3
  interaction_weight: 0.4
  state_weight: 0.3
  resonance_weight: 0.5

# Logging Configuration
logging:
  level: "INFO"
  file: "logs/simulation.log"
  rotation: "1 day"
  max_size: "10MB"

# Security Settings
security:
  max_api_calls: 1000
  rate_limit: 100
  timeout: 30
  retry_attempts: 3

# Ethical Constraints
ethics:
  max_simulation_time: 3600  # seconds
  data_retention_days: 30
  privacy_level: "high"
  audit_logging: true 